import { useEffect, useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import SearchableSelect from "@/components/common/SearchableSelect";
type Country={code:string;iso3?:string;name:string;callingCode:string;flag:string};
const FALLBACK:Country[]=[["CI","CIV","Côte d’Ivoire","+225","🇨🇮"],["FR","FRA","France","+33","🇫🇷"],["US","USA","États-Unis","+1","🇺🇸"],["CA","CAN","Canada","+1","🇨🇦"],["BE","BEL","Belgique","+32","🇧🇪"],["CH","CHE","Suisse","+41","🇨🇭"],["GB","GBR","Royaume-Uni","+44","🇬🇧"],["SN","SEN","Sénégal","+221","🇸🇳"],["GN","GIN","Guinée","+224","🇬🇳"],["BF","BFA","Burkina Faso","+226","🇧🇫"],["ML","MLI","Mali","+223","🇲🇱"],["CM","CMR","Cameroun","+237","🇨🇲"],["TG","TGO","Togo","+228","🇹🇬"],["BJ","BEN","Bénin","+229","🇧🇯"]].map(([code,iso3,name,callingCode,flag])=>({code,iso3,name,callingCode,flag})) as Country[];
const flag=(code:string)=>code.toUpperCase().replace(/./g,c=>String.fromCodePoint(127397+c.charCodeAt(0)));
export interface CountryPhoneInputProps{label:string;countryCode?:string;localValue?:string;required?:boolean;disabled?:boolean;onChange:(v:{countryCode:string;callingCode:string;localValue:string;internationalValue:string})=>void;minLocalDigits?:number;maxLocalDigits?:number}
export const CountryPhoneInput=({label,countryCode="CI",localValue="",required,disabled,onChange,minLocalDigits,maxLocalDigits}:CountryPhoneInputProps)=>{
 const [countries,setCountries]=useState<Country[]>(FALLBACK);
 useEffect(()=>{const cached=localStorage.getItem("agricapital:countries:v1");if(cached){try{const p=JSON.parse(cached);if(Array.isArray(p)&&p.length>150)setCountries(p)}catch (error) { console.warn("[CountryPhoneInput] cache pays invalide", error); }}
 fetch("https://restcountries.com/v3.1/all?fields=name,cca2,idd,flags").then(r=>r.ok?r.json():Promise.reject()).then((rows:any[])=>{const mapped=rows.map(r=>({code:r.cca2,iso3:r.cca3,name:r.name?.common||r.cca2,callingCode:r.idd?.root?(r.idd.root+(r.idd.suffixes?.[0]||"")):"",flag:r.flags?.emoji||flag(r.cca2)})).filter((c:Country)=>c.callingCode).sort((a,b)=>a.name.localeCompare(b.name,"fr"));if(mapped.length>150){setCountries(mapped);localStorage.setItem("agricapital:countries:v1",JSON.stringify(mapped))}}).catch(()=>undefined)},[]);
 const selected=countries.find(c=>c.code===countryCode)||countries.find(c=>c.callingCode===countryCode)||countries.find(c=>c.code==="CI")||countries[0];
 const resolvedMin=minLocalDigits ?? (selected?.callingCode === "+225" ? 10 : 7);
 const resolvedMax=maxLocalDigits ?? (selected?.callingCode === "+225" ? 10 : 15);
 const options=useMemo(()=>countries.map(c=>({value:c.code,label:c.flag+" "+c.name+" "+c.callingCode})),[countries]);
 return <div className="space-y-2 min-w-0">{label && <label className="text-sm font-medium truncate block">{label}{required&&" *"}</label>}<div className="flex w-full min-w-0 items-stretch gap-2"><SearchableSelect value={selected?.code||countryCode} onValueChange={code=>{const c=countries.find(x=>x.code===code)||selected;const local=localValue.slice(0,resolvedMax);onChange({countryCode:c.code,callingCode:c.callingCode,localValue:local,internationalValue:c.callingCode+local.replace(/\D/g,"")})}} options={options} placeholder="Pays" searchPlaceholder="Rechercher un pays..." disabled={disabled} className="w-[88px] min-[390px]:w-[104px] sm:w-[120px] shrink-0" triggerLabel={(selected?.flag || "🌐") + " " + (selected?.callingCode || "")} /><Input className="min-w-0 flex-1" type="tel" inputMode="numeric" autoComplete="tel" value={localValue} disabled={disabled} required={required} minLength={resolvedMin} maxLength={resolvedMax} placeholder={selected?.callingCode === "+225" ? "10 chiffres" : "Numéro local"} onChange={e=>{const local=e.target.value.replace(/\D/g,"").slice(0,resolvedMax);onChange({countryCode:selected.code,callingCode:selected.callingCode,localValue:local,internationalValue:selected.callingCode+local})}}/></div></div>;
};
export default CountryPhoneInput;